name = "stellot-dagger"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables â€” set these in the Cloudflare dashboard for production
# or in a .dev.vars file for local development
# stellar contract build

# stellar contract deploy \
#   --wasm target/wasm32v1-none/release/election.wasm \
#   --source deploy \
#   --network testnet
#
[vars]
NEXT_PUBLIC_RPC_URL = "https://soroban-testnet.stellar.org"
NEXT_PUBLIC_NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
NEXT_PUBLIC_CONTRACT_ID = "CA4AN5OHAHRH3WMRPPEIAY73ANJIWLDGRLWINB4TVUVASTMWFEGGQO5N"
